### ISSUE TITLE
Typo?  "doesn't really make sense" -> "doesn't really matter"

### ISSUE THREAD

**Issue by tim-seoss** [jamesmunns/embedded-the-missing-parts#4]
Not sure if this is a typo or not:

In section 2.4 "A Style Guide":

"Now, I'm going to start off by saying: the actual style you choose doesn't really make sense. Tabs, spaces, same line brackets, whatever. Do whatever your team can agree on."

Was that intended to be "the actual style you choose doesn't really **matter**"?

**Comment by jamesmunns** [comment]
Yes! Feel free to PR this :)
